#!/usr/bin/env python3
"""
ReportGenius - The Singularity Engine
Generates all client deliverables from audit data.
Memory-optimized with streaming writes to avoid loading entire HTML in RAM.
"""

import json
import os
import datetime
from pathlib import Path
from jinja2 import Template

# Minimal HTML template that creates the "Digital Twin" attack simulation
# Uses D3.js loaded from CDN (no local storage for 5MB library)
EXECUTIVE_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FortifyOne Audit Report - {{ client_name }}</title>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <style>
        body { font-family: 'Segoe UI', sans-serif; margin: 0; padding: 20px; background: #0a0e27; color: #e0e6ed; }
        .container { max-width: 900px; margin: 0 auto; }
        .header { text-align: center; padding: 30px; background: linear-gradient(135deg, #1a1f3a, #0d1126); border-radius: 10px; margin-bottom: 30px; }
        .header h1 { color: #00d4ff; margin: 0; }
        .header .tagline { color: #8892b0; font-size: 0.9em; }
        .metric-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 30px; }
        .metric-card { background: #1a1f3a; padding: 20px; border-radius: 8px; text-align: center; border-left: 4px solid #00d4ff; }
        .metric-card.critical { border-left-color: #ff4757; }
        .metric-card.warning { border-left-color: #ffa502; }
        .metric-value { font-size: 2.5em; font-weight: bold; color: #00d4ff; }
        .metric-label { color: #8892b0; font-size: 0.85em; margin-top: 5px; }
        #simulation { background: #1a1f3a; border-radius: 10px; padding: 20px; min-height: 400px; margin-bottom: 30px; }
        .finding { background: #1a1f3a; padding: 15px; border-radius: 8px; margin-bottom: 10px; border-left: 4px solid #ff4757; }
        .finding.medium { border-left-color: #ffa502; }
        .finding h3 { margin: 0 0 5px 0; color: #fff; }
        .finding p { margin: 0; color: #8892b0; font-size: 0.9em; }
        .controls { text-align: center; margin: 20px 0; }
        .btn { background: #00d4ff; color: #0a0e27; border: none; padding: 12px 25px; border-radius: 5px; font-size: 1em; cursor: pointer; font-weight: bold; }
        .btn:hover { background: #00b8e6; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🛡️ FortifyOne Audit Report</h1>
            <p class="tagline">{{ client_name }} | {{ date }} | TrinityTech Digital Defense</p>
        </div>
        
        <div class="metric-grid">
            <div class="metric-card {% if risk_score > 70 %}critical{% elif risk_score > 40 %}warning{% endif %}">
                <div class="metric-value">{{ risk_score }}%</div>
                <div class="metric-label">Overall Risk Score</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{{ open_ports }}</div>
                <div class="metric-label">Exposed Services</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{{ compliance }}%</div>
                <div class="metric-label">Policy Compliance</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{{ breach_count }}</div>
                <div class="metric-label">Credential Exposures</div>
            </div>
        </div>
        
        <div id="simulation">
            <h2 style="color: #00d4ff; margin-top: 0;">🔴 Attack Path Simulation</h2>
            <div id="viz"></div>
            <div class="controls">
                <button class="btn" onclick="animateAttack()">▶ Simulate Breach</button>
                <p id="impact-estimate" style="color: #ff4757; margin-top: 15px; display: none;"></p>
            </div>
        </div>
        
        <h2 style="color: #ff4757;">Critical Findings</h2>
        {% for finding in findings %}
        <div class="finding {{ finding.severity }}">
            <h3>{{ finding.title }}</h3>
            <p>{{ finding.description }}</p>
            <p><strong>Remediation:</strong> {{ finding.remediation }}</p>
        </div>
        {% endfor %}
        
        <p style="text-align: center; color: #8892b0; margin-top: 40px; font-size: 0.8em;">
            Generated by FortifyOne | TrinTech Digital Defense | {{ generation_date }}
        </p>
    </div>
    
    <script>
        // D3.js visualization of the attack path
        const width = document.getElementById('viz').clientWidth;
        const height = 350;
        
        const svg = d3.select('#viz')
            .append('svg')
            .attr('width', width)
            .attr('height', height);
        
        // Define nodes: Internet -> Firewall -> Workstation -> Server
        const nodes = [
            {id: 'internet', label: '🌐 Internet (Attacker)', x: 100, y: 175},
            {id: 'firewall', label: '🧱 Firewall', x: 300, y: 100},
            {id: 'workstation', label: '💻 Reception PC', x: 500, y: 60},
            {id: 'server', label: '🗄️ Patient Records Server', x: 700, y: 175}
        ];
        
        const links = [
            {source: 'internet', target: 'firewall', label: 'Port {{ open_port }} OPEN'},
            {source: 'firewall', target: 'workstation', label: 'Phishing Email'},
            {source: 'workstation', target: 'server', label: 'Lateral Movement'}
        ];
        
        // Draw links
        svg.selectAll('line')
            .data(links)
            .enter()
            .append('line')
            .attr('x1', d => nodes.find(n => n.id === d.source).x)
            .attr('y1', d => nodes.find(n => n.id === d.source).y)
            .attr('x2', d => nodes.find(n => n.id === d.target).x)
            .attr('y2', d => nodes.find(n => n.id === d.target).y)
            .attr('stroke', '#2d3561')
            .attr('stroke-width', 3)
            .attr('stroke-dasharray', '8,4');
        
        // Draw nodes
        const nodeGroup = svg.selectAll('g')
            .data(nodes)
            .enter()
            .append('g')
            .attr('transform', d => `translate(${d.x},${d.y})`);
        
        nodeGroup.append('circle')
            .attr('r', 30)
            .attr('fill', '#1a1f3a')
            .attr('stroke', '#00d4ff')
            .attr('stroke-width', 2);
        
        nodeGroup.append('text')
            .attr('text-anchor', 'middle')
            .attr('dy', 5)
            .attr('fill', '#e0e6ed')
            .text(d => d.id);
        
        nodeGroup.append('text')
            .attr('text-anchor', 'middle')
            .attr('dy', 50)
            .attr('fill', '#8892b0')
            .attr('font-size', '10px')
            .text(d => d.label);
        
        // Animation function
        function animateAttack() {
            const linkLines = svg.selectAll('line');
            let delay = 0;
            
            linkLines.each(function(d, i) {
                const line = d3.select(this);
                setTimeout(() => {
                    line.attr('stroke', '#ff4757')
                        .attr('stroke-width', 5)
                        .attr('stroke-dasharray', '0')
                        .transition()
                        .duration(500)
                        .attr('stroke', '#ff4757');
                }, delay);
                delay += 1000;
            });
            
            setTimeout(() => {
                document.getElementById('impact-estimate').style.display = 'block';
                document.getElementById('impact-estimate').innerHTML = 
                    '⚠ Estimated Impact: <strong>${{ estimated_loss }}</strong> in downtime and recovery costs over <strong>{{ downtime_days }}</strong> days';
            }, delay);
        }
    </script>
</body>
</html>
"""

def generate_executive_report(audit_data: dict, output_dir: str) -> str:
    """Generate the interactive HTML executive report."""
    
    client_name = audit_data["audit_metadata"]["client_name"]
    external = audit_data.get("external_scan", {})
    policy = audit_data.get("policy_compliance", {})
    breach = audit_data.get("breach_exposure", {})
    
    # Calculate metrics
    risk_score = external.get("risk_score", 0)
    open_ports = len(external.get("open_ports", []))
    compliance = policy.get("overall_compliance_percentage", 0)
    breach_count = breach.get("compromised_credentials", 0)
    
    # Find the most dangerous open port for the simulation
    open_port = "3389"
    if open_ports > 0:
        open_port = external["open_ports"][0].get("port", "3389")
    
    # Build findings list
    findings = []
    for port_info in external.get("open_ports", []):
        findings.append({
            "title": f"Port {port_info['port']} ({port_info['service']}) Exposed to Internet",
            "description": f"Critical service visible to attackers. Risk level: {port_info.get('risk_level', 'unknown')}",
            "remediation": f"Close port {port_info['port']} or restrict access to authorized IP addresses only.",
            "severity": "critical" if port_info.get("risk_level") == "high" else "medium"
        })
    
    # Render template
    template = Template(EXECUTIVE_REPORT_TEMPLATE)
    html_content = template.render(
        client_name=client_name,
        date=audit_data["audit_metadata"]["date"],
        risk_score=risk_score,
        open_ports=open_ports,
        compliance=compliance,
        breach_count=breach_count,
        open_port=open_port,
        estimated_loss=f"${risk_score * 1500:,}",
        downtime_days=max(1, risk_score // 10),
        findings=findings,
        generation_date=datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    )
    
    # Write to file
    filename = f"{client_name.replace(' ', '_')}_Executive_Report.html"
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, 'w') as f:
        f.write(html_content)
    
    return filepath

def generate_remediation_plan(audit_data: dict, output_dir: str) -> str:
    """Generate remediation plan as CSV for easy import into project management tools."""
    
    client_name = audit_data["audit_metadata"]["client_name"]
    external = audit_data.get("external_scan", {})
    
    filename = f"{client_name.replace(' ', '_')}_Remediation_Plan.csv"
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, 'w') as f:
        f.write("Priority,Finding,Category,Risk Score,Estimated Effort,Status\n")
        
        priority = 1
        for port in external.get("open_ports", []):
            f.write(f"{priority},Close port {port['port']} ({port['service']}),Network Security,{port.get('risk_level', 'medium')},2 hours,Not Started\n")
            priority += 1
        
        # Add policy-based remediations
        f.write(f"{priority},Implement Multi-Factor Authentication for all users,Access Control,Critical,8 hours,Not Started\n")
    
    return filepath

if __name__ == "__main__":
    test_data = {
        "audit_metadata": {
            "client_name": "Test Medical Practice",
            "date": "2024-01-15",
            "domain": "testmed.com"
        },
        "external_scan": {
            "open_ports": [
                {"port": "3389", "service": "ms-wbt-server", "risk_level": "high"},
                {"port": "445", "service": "microsoft-ds", "risk_level": "high"},
                {"port": "22", "service": "ssh", "risk_level": "medium"}
            ],
            "risk_score": 85
        },
        "policy_compliance": {
            "overall_compliance_percentage": 45
        },
        "breach_exposure": {
            "compromised_credentials": 7
        }
    }
    
    output_dir = "/tmp/fortifyone_test"
    os.makedirs(output_dir, exist_ok=True)
    
    report_path = generate_executive_report(test_data, output_dir)
    print(f"Report generated: {report_path}")
